### ISSUE TITLE
Scan Fails with pycurl.error: cannot invoke setopt() - no curl handle

### ISSUE THREAD

**Issue by ossie-git** [xmendez/wfuzz#120]
# Issue template

## Context

**Please check:**

- [X] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: Output of wfuzz --version

2.3.4

Python version: Output of python --version

Python 2.7.15rc1

Python 3 is also installed: Python 3.6.7

OS: Ubuntu 18.04.1 LTS

## Report

**What is the current behavior?**

wfuzz exits without completing the scan and throws a: "pycurl.error: cannot invoke setopt() - no curl handle" error.  A similar issue is found here - https://github.com/xmendez/wfuzz/issues/75 - but that ticket refers to accessing it programmatically.  This behavior is repeated when I repeat the scan with the same parameters

I run the following scan:

```
wfuzz -c --hc 404,500 -w wordlist.txt https://www.example.com/FUZZ
```

After some scanning, it throws the following error:

```
000371:  C=200     31 L       55 W          701 Ch        "."
003010:  C=500     44 L      213 W         2058 Ch        "albums.php"
Fatal exception: Pycurl error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.example.com:443
Exception in thread _read_retry_queue:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wfuzz/myhttp.py", line 179, in _read_retry_queue
    self.enqueue(res, poolid)
  File "/usr/local/lib/python3.6/dist-packages/wfuzz/myhttp.py", line 87, in enqueue
    c = fuzzres.history.to_http_object(self.freelist.get())
  File "/usr/local/lib/python3.6/dist-packages/wfuzz/fuzzobjects.py", line 399, in to_http_object
    return Request.to_pycurl_object(c, self._request)
  File "/usr/local/lib/python3.6/dist-packages/wfuzz/externals/reqresp/Request.py", line 287, in to_pycurl_object
    c.setopt(pycurl.MAXREDIRS, 5)
pycurl.error: cannot invoke setopt() - no curl handle
```

**What is the expected or desired behavior?**

The scan should complete successfully

**Please provide steps to reproduce, including exact wfuzz command executed and output:**

Refer to the above

**Other relevant information:**

X

**Comment by xmendez** [comment]
Hi, 

Any chances that you can share the URL failing? it seems a problem with SSL.

Cheers

**Comment by naripok** [comment]
Hi guys,
I'm trying to fuzz the Postman box, from 'hackthebox', and I'm getting a similar issue.

```
uname -all
linux-kali-5.3.0-kali3-amd64 #1 SMP Debian-5.3.15-1kali1 (2019-12-09) x86_64 GNU/Linux
```

using the command with kali's install of wfuzz:
```
python -V  
Python 2.7.17
```
```
wfuzz --version 
warning: Pycurl was not compiled against OpenSSL. Wfuzz may not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.
2.4
```
`wfuzz -c -w ~/SecLists/Passwords/(pick a list) https://10.10.10.160/FUZZ`

the scan fail to start and return the error:
`Fatal exception: Pycurl error 56: GnuTLS recv error (-110): The TLS connection was non-properly terminated`
and spits out the same stack trace as OP.

So I tried to compile pycurl against OpenSSL ans give it a try, also using the last version of wfuzz:
```
python -V  
Python 3.7.5
```
```
wfuzz --version 
2.4.2
```
`wfuzz -c -w ~/SecLists/Passwords/(pick a list) https://10.10.10.160/FUZZ`

the scan fail to start and return the error:
`Fatal exception: Pycurl error 56: Open_SSL SSL_read: Success`

and spits out the same stack trace as OP also.

If I try to use it for non https sites, it works flawlessly.
Also, if I try to fuzz google by https, it also works, so it is not a SSL thing nether.

There is one importante thing, I believe, I noticed: When I try to visit the site using the browser (firefox), it gives me the error:
`MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT`

I'm willing to help to debug this issue, so if there is anything I can do to help, let me know.
I love your tool and dont wanna live without it lool.

Thx fellow.
