### ISSUE TITLE
pip install wfuzz error

### ISSUE THREAD

**Issue by M0dred** [xmendez/wfuzz#133]
Collecting pycurl (from wfuzz)
  Using cached https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iPajo7/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-iPajo7/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-iPajo7/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/tmp/pip-install-iPajo7/pycurl/setup.py", line 227, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-iPajo7/pycurl/

$python -V
Python 2.7.16

$uname -a
Linux 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

**Comment by macintorsten** [comment]
Running this command first helped for me: `apt install libcurl4-openssl-dev libssl-dev`

**Comment by m0nk3y-s3c** [comment]
> Running this command first helped for me: `apt install libcurl4-openssl-dev libssl-dev`

THANKS!!!!!
