### ISSUE TITLE
Failed to run wfuzz using crontab

### ISSUE THREAD

**Issue by IgorSasovets** [xmendez/wfuzz#170]
# Issue template

## Context
I'm trying to setup automatic wfuzz runs for local application but every wfuzz run fails. When I do it manually through the terminal window, all works as expected. 

**Please check:**

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: Output of wfuzz --version
2.4

Python version: Output of python --version
2.7

OS: MacOS High Sierra

## Report

**What is the current behavior?**

wfuzz run fails

**What is the expected or desired behavior?**

successful wfuzz run

**Please provide steps to reproduce, including exact wfuzz command executed and output:**

setup a simple script for wfuzz runs as below
```
#!/usr/bin/env bash
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/
VALID_TOKEN=12312dfdsmmmb11231
wfuzz -w common.txt --hc=404,401,400,403 -H "Auth: $VALID_USER_TOKEN" -u http://localhost:3200/api/FUZZ --field r 2>&1 | tee -a fuzzer_run_results_common.txt
```

setup crontask to run the script

**Other relevant information:**

traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/wfuzz", line 11, in <module>
    load_entry_point('wfuzz==2.4', 'console_scripts', 'wfuzz')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/wfuzz.py", line 8, in <module>
    from .ui.console.mvc import Controller, KeyPress, View
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/mvc.py", line 143, in <module>
    class View:
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/mvc.py", line 144, in View
    widths = [10, 8, 6, 6, 9, getTerminalSize()[0] - 65]
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/output.py", line 80, in getTerminalSize
    tuple_xy = _getTerminalSize_linux()
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/output.py", line 154, in _getTerminalSize_linux
    return int(cr[1]), int(cr[0])
TypeError: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/bin/wfuzz", line 11, in <module>
    load_entry_point('wfuzz==2.4', 'console_scripts', 'wfuzz')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/wfuzz.py", line 8, in <module>
    from .ui.console.mvc import Controller, KeyPress, View
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/mvc.py", line 143, in <module>
    class View:
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/mvc.py", line 144, in View
    widths = [10, 8, 6, 6, 9, getTerminalSize()[0] - 65]
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/output.py", line 80, in getTerminalSize
    tuple_xy = _getTerminalSize_linux()
  File "/usr/local/lib/python2.7/site-packages/wfuzz-2.4-py2.7.egg/wfuzz/ui/console/output.py", line 154, in _getTerminalSize_linux
    return int(cr[1]), int(cr[0])
```

**Comment by IgorSasovets** [comment]
@xmendez , this can be fixed by adding a new option. Something like `default-terminal-size`. Error occurred due to the below lines (`wfuzz/src/wfuzz/ui/console/output.py`):
```
if current_os == 'Linux' or current_os == 'Darwin' or current_os.startswith('CYGWIN'):
        tuple_xy = _getTerminalSize_linux()
    if tuple_xy is None:
        print("default")
        tuple_xy = (80, 25)      # default value

    return tuple_xy
```

**Comment by IgorSasovets** [comment]
I think this issue can be fixed by adding a separate option to set the default terminal window size if needed.
