### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by M0dred** [xmendez/wfuzz#202]
When I type wfuzz
Then show the error. My python version is Python 2.7.18

Type wfuzz -h for further information or --help for advanced usage.
Traceback (most recent call last):
  File "/usr/local/bin/wfuzz", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/wfuzz.py", line 63, in main
    Facade().sett.save()
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/utils.py", line 123, in __call__
    class_.instance = super(Singleton, class_).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/facade.py", line 65, in __init__
    self.sett = Settings()
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/externals/settings/settings.py", line 15, in __init__
    self.cparser = ConfigParser()
TypeError: 'module' object is not callable

**Comment by MikeMeliz** [comment]
Not a dev, but it seems you're missing ConfigParser: `pip install ConfigParser`

**Comment by xmendez** [comment]
If you have downloaded the source code, you should install all the required depencencies.
I would recommend you to use pip install wfuzz instead.
