### ISSUE TITLE
python3.8 pkg_resources.py

### ISSUE THREAD

**Issue by umiterkol** [xmendez/wfuzz#228]
wfuzz 
Traceback (most recent call last):
  File "/usr/bin/wfuzz", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by xmendez** [comment]
Hi @umiterkol , 

Have you install all the required libraries before executing wfuzz?

cheers
