### ISSUE TITLE
wfuzz on mac returning exceptions

### ISSUE THREAD

**Issue by mankomal** [xmendez/wfuzz#253]
# Issue template

Hello, 
while executing command wfuzz in terminal on Mac OSX I am getting following error
% wfuzz
 /usr/local/lib/python2.7/site-packages/wfuzz/__init__.py:35: UserWarning:Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.
Traceback (most recent call last):
  File "/usr/local/bin/wfuzz", line 5, in <module>
    from wfuzz.wfuzz import main
  File "/usr/local/lib/python2.7/site-packages/wfuzz/__init__.py", line 55, in <module>
    from .options import FuzzSession
  File "/usr/local/lib/python2.7/site-packages/wfuzz/options.py", line 6, in <module>
    from .facade import (
  File "/usr/local/lib/python2.7/site-packages/wfuzz/facade.py", line 65
    class Facade(metaclass=Singleton):
                          ^
SyntaxError: invalid syntax

(PS: The Syntax error pointer is coming on = equal sign of the line      class Facade(metaclass=Singleton):)

I am running following environment

Python 2.7.17
Python 3.8.6
Mac OS Big Sur version 11.0.1

**Comment by xmendez** [comment]
Hi,

It seems that you're using Python 2? It is not longer supported.

Cheers

**Comment by zesty** [comment]
can close this, yes?
