### ISSUE TITLE
eror install wfuzz

### ISSUE THREAD

**Issue by Joni321pku** [xmendez/wfuzz#349]
Collecting wfuzz
  Using cached wfuzz-3.1.0-py3-none-any.whl (148 kB)
Collecting chardet
  Using cached chardet-5.1.0-py3-none-any.whl (199 kB)
Collecting pycurl
  Using cached pycurl-7.45.2.tar.gz (234 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\aldiirsad\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 12, in <module>
          import setuptools.version
        File "C:\Users\aldiirsad\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\aldiirsad\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 77, in <module>
          __import__('pkg_resources.extern.packaging.requirements')
        File "C:\Users\aldiirsad\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 9, in <module>
          from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
        File "C:\Users\aldiirsad\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
          __import__(extant)
        File "C:\Users\aldiirsad\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 943, in <module>
          collections.MutableMapping.register(ParseResults)
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.nt:**

Wfuzz version: Output of wfuzz --version

Python version: Output of python --version

OS: X

## Report

**What is the current behavior?**

X

**What is the expected or desired behavior?**

X

**Please provide steps to reproduce, including exact wfuzz command executed and output:**

X

**Other relevant information:**

X

**Comment by rg0815** [comment]
this worded for me (win10)

try to install it with the parameter --use-deprecated=backtrack-on-build-failures
-> pip install wfuzz --use-deprecated=backtrack-on-build-failures
