### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by Luky12568** [xmendez/wfuzz#354]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/wfuzz", line 5, in <module>
    from wfuzz.wfuzz import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wfuzz/__init__.py", line 55, in <module>
    from .options import FuzzSession
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wfuzz/options.py", line 6, in <module>
    from .facade import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wfuzz/facade.py", line 1, in <module>
    from .helpers.file_func import get_home, get_path, get_config_dir
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wfuzz/helpers/file_func.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
If it helps i am on termux

**Comment by Luky12568** [comment]
Just do pip install --upgrade setuptools if anyone encounters it
