### ISSUE TITLE
ImportError: No module named resource

### ISSUE THREAD

**Issue by daimondd33** [xmendez/wfuzz#6]
I have this error with running "C:\wfuzz-2.1.2\wfuzz.py" in windows

Traceback (most recent call last):
  File "C:\wfuzz-2.1.2\wfuzz.py", line 6, in <module>
    from framework.fuzzer.Fuzzer import Fuzzer
  File "C:\wfuzz-2.1.2\framework\fuzzer\Fuzzer.py", line 12, in <module>
    from framework.utils.myqueue import MyPriorityQueue
  File "C:\wfuzz-2.1.2\framework\utils\myqueue.py", line 1, in <module>
    import resource
ImportError: No module named resource

**Comment by xmendez** [comment]
Thanks. This import can be removed as it is not used anymore.
