### ISSUE TITLE
Install is not working on Cygwin64

### ISSUE THREAD

**Issue by riramar** [xmendez/wfuzz#61]
```
$ pip install wfuzz
Collecting wfuzz
  Downloading wfuzz-2.2.8.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 1.4MB/s
Collecting pycurl (from wfuzz)
  Downloading pycurl-7.43.0.tar.gz (182kB)
    100% |████████████████████████████████| 184kB 1.7MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-IMKmtm/pycurl/setup.py", line 823, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-IMKmtm/pycurl/setup.py", line 497, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-IMKmtm/pycurl/setup.py", line 71, in __init__
        self.configure()
      File "/tmp/pip-build-IMKmtm/pycurl/setup.py", line 107, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IMKmtm/pycurl/
```

**Comment by xmendez** [comment]
Hi,

To be honest I have not tried to install wfuzz in cygwin using pip but in any case that's a pycurl installation failure not wfuzz.

cheers
