### ISSUE TITLE
IOError while fuzzing

### ISSUE THREAD

**Issue by phackt** [xmendez/wfuzz#66]
Version: 2.2.8

Command:
```
wfuzz --script=backups -z file,/root/Documents/repo/SecLists/Discovery/Web_Content/quickhits.txt -Z --conn-delay 5 --req-delay 5 --follow --hc 401,403,404,500 https://loop.brusselsairlines.com/FUZZ
```

Error:
```
006069:  C=404     30 L	      44 W	    822 Ch	  "//web-console/.bakServerInfo"Exception in thread _read_multi_stack:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/myhttp.py", line 194, in _read_multi_stack
    res.history.from_http_object(c, buff_header.getvalue(), buff_body.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/fuzzobjects.py", line 380, in from_http_object
    return self._request.response_from_conn_object(c, bh, bb)
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/externals/reqresp/Request.py", line 341, in response_from_conn_object
    rp.parseResponse(header)
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/externals/reqresp/Response.py", line 153, in parseResponse
    body=gzipper.read()
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

I launched several instances of Wfuzz in parallel.

**Comment by phackt** [comment]
Ok the problem persists even with one single instance of wfuzz and the option ```-t 1```. Also it could be great with ```--script=backups``` to not add a backup extension when we are fuzzing a folder (ex of payload /phpmyadmin/.tar.gz).

Cheers,
