### ISSUE TITLE
 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3txvCv/pycurl/

### ISSUE THREAD

**Issue by PeterWilsonIFS** [xmendez/wfuzz#81]
try pip install I get this error

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3txvCv/pycurl/

full trace is 
Collecting pycurl
  Using cached https://files.pythonhosted.org/packages/77/d9/d272b38e6e25d2686e22f6058820298dadead69340b1c57ff84c87ef81f0/pycurl-7.43.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3txvCv/pycurl/setup.py", line 841, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-3txvCv/pycurl/setup.py", line 508, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-3txvCv/pycurl/setup.py", line 72, in __init__
        self.configure()
      File "/tmp/pip-build-3txvCv/pycurl/setup.py", line 108, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

Any Ideas?

**Comment by PeterWilsonIFS** [comment]
this was some dependances I did not have installed

**Comment by davesdere** [comment]
What were they? I got the same issue

**Comment by honeybirdhk** [comment]
@davesdere , try install pycurl.  I did and it worked.
