### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by kirtiso** [xmendez/wfuzz#88]
hello sir,

when i'am installing on windows7 it give some error , and i don't understand so can u help for proper installation please.
D:\wfuzz-master>wfuzz -z help
Traceback (most recent call last):
  File "C:\Python27\Scripts\wfuzz-script.py", line 11, in <module>
    load_entry_point('wfuzz==2.3', 'console_scripts', 'wfuzz')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2693, in
load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2324, in
load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2330, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\wfuzz-2.3-py2.7.egg\wfuzz\__init__.py", li
ne 34, in <module>
    from .api import fuzz, get_payload, get_payloads, encode, decode, payload, g
et_session
  File "c:\python27\lib\site-packages\wfuzz-2.3-py2.7.egg\wfuzz\api.py", line 3,
 in <module>
    from .ui.console.clparser import CLParser
  File "c:\python27\lib\site-packages\wfuzz-2.3-py2.7.egg\wfuzz\ui\console\clpar
ser.py", line 9, in <module>
    from .common import help_banner
  File "c:\python27\lib\site-packages\wfuzz-2.3-py2.7.egg\wfuzz\ui\console\commo
n.py", line 5, in <module>
    import WConio
ImportError: No module named WConio

D:\wfuzz-master>

**Comment by hu-qi** [comment]
I encountered the same problem. How did you solve it?@kirtiso

**Comment by kirtiso** [comment]
hey,
still not resolve this problem.

**Comment by DongDuong8E** [comment]
Same with me

**Comment by kirtiso** [comment]
Hey,
My problem is resolve , i'am remove previous wfuzz and again install new wfuzz then open and apply
$ pip install wfuzz
$ python setup.py install

it will successfully running.
